spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springsecuritycourse
    username: root
    password: Kappa123
  jpa:
    properties:
      hibernate:
        ddl: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG